### ISSUE TITLE
A fastcore `test_stdout` test works in the notebook and works with nbdev_test_nbs, but fails using nbprocess_test

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/nbprocess#108]
I have a printed output test (copied from fastai) that works in the notebook and works with `nbdev_test_nbs`, but errors out using `nbprocess_test`.

It can be found in this [notebook](https://github.com/warner-benjamin/fastxtend/blob/main/nbs/metrics.ipynb), cell 50: 
```python
learn = synth_learner(n_trn=5, metrics=TestAvg())
pat = r"\[\d, \d+.\d+, \d+.\d+, \d+.\d+, '\d\d:\d\d'\]"
test_stdout(lambda: learn.fit(1), pat, regex=True)
```
The original test is from fastai's [13a_learner.ipynb](https://github.com/fastai/fastai/blob/master/nbs/13a_learner.ipynb) and I assume that it also fails (however, I have not verified it fails).
```python
learn = synth_learner(n_train=5, metrics=tst_metric)
pat = r"\[\d, \d+.\d+, \d+.\d+, \d+.\d+, '\d\d:\d\d'\]"
test_stdout(lambda: learn.fit(1), pat, regex=True)
```

The error log doesn't look helpful, but am posting it for completeness.
```
WARNING:root:AssertionError in /fastxtendnp/nbs/metrics.ipynb:
===========================================================================

While Executing Cell #50:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-ab2039eed6f1> in <module>
      3 # pat = r"[tensor\(\d.\d*\), tensor\(\d.\d*\), tensor\(\d.\d*\), 'dd:dd']"
      4 pat = r"\[\d, \d+.\d+, \d+.\d+, \d+.\d+, '\d\d:\d\d'\]"
----> 5 test_stdout(lambda: learn.fit(1), pat, regex=True)

~/miniconda3/lib/python3.9/site-packages/fastcore/test.py in test_stdout(f, exp, regex)
     78     s = io.StringIO()
     79     with redirect_stdout(s): f()
---> 80     if regex: assert re.search(exp, s.getvalue()) is not None
     81     else: test_eq(s.getvalue(), f'{exp}\n' if len(exp) > 0 else '')
     82 

AssertionError: 


nbprocess Tests Failed On The Following Notebooks:
==================================================
        metrics.ipynb
```

**Comment by seeM** [comment]
@warner-benjamin, via @jph00 on discord:

> i've just added a `default_cbs:bool=True` param to `Learner`. If you set it to `False` in that failing test, and manually just add the minimal needed callbacks, hopefully that'll fix the failing test you were having trouble with

If that works, I think it's okay to close this? cc @hamelsmu

**Comment by jph00** [comment]
No I need to fix the test first
