### ISSUE TITLE
Wrongly formed links to github repo in generated docs

### ISSUE THREAD

**Issue by vguerra** [fastai/nbprocess#115]
Hello! :) .. this is my first time reporting an issue here, so I would like to thank you first for this package, it makes so much simplier the handling of notebooks and automatic generation of documentation.

Now, the issue I am seeing is in the resulting html docs generated by `quarto`, I noticed that there are some issues with the urls that point to the github repo. For instance, the link to create a new github issue that appears on the right-side navigation bar is wrong.

After having a look at the automatically generated `_quarto.yml` file, the `website.repo-url` property points to the github repo
but includes as well info about the branch the checkout is coming from. According to quarto sources, this property should point to the  base URL only (ref [here](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/schema/definitions.yml#L485-L487)).

This URL comes from the `settings.ini` file, specified in the property `git_url` and having a look at the [template](https://github.com/fastai/nbprocess-template/blob/master/settings.ini) I see that it is defined as follows:

```bash
git_url = https://github.com/%(user)s/%(lib_name)s/tree/%(branch)s/
```

So I wonder if having the branch info in there is useful somewhere out of the docs? As far as I can see the only usage of `git_url` is for the docs only, but maybe I am missing something? . As well, there is one more tiny issue with how this is defined, mainly, it is using the `lib_name` for the repo name. This is problematic b/c the `lib_name` is coming from the name of the repo, but
with all `-`s substituted by `_`s (ref [here](https://github.com/fastai/nbprocess/blob/master/nbprocess/cli.py#L211)). In my case, I named my repo `fastbook-notes` so all links end up pointing to `https://github.com/vguerra/fastbook_notes/....`.

If you think that having the `git_url` property represent the base URL to the github repo is Ok, I can open a couple of pull requests to fix it using the following commits:

* [Fix in `nbprocess-template`.](https://github.com/vguerra/nbprocess-template/commit/b1fd294b23f7711cec8f481f0d78d295d9206457)
* [Fix for configuration extracted from the git repo.](https://github.com/vguerra/nbprocess/commit/8b4350208ae7c80d371d4624589a05a7f1deda9d)

**Comment by vguerra** [comment]
the issue is as well visible from the nbprocess docs: https://nbprocess.fast.ai/ .. link on *Report an issue* on the right navbar.

**Comment by hamelsmu** [comment]
Thanks for the fix
