### ISSUE TITLE
Difference between `preview` and `serve`

### ISSUE THREAD

**Issue by deven367** [fastai/nbprocess#74]
Hello, the nbprocess tutorial has 2 sections, `Preview the docs`
![image](https://user-images.githubusercontent.com/31466137/174496103-23119fbf-c4df-42c4-ae9c-55f9d1a3642b.png)
and 

`View docs locally`
![image](https://user-images.githubusercontent.com/31466137/174496119-dd7e9da4-2750-4231-9803-997c0e12a9b9.png)

I'm not sure if they're meant to be different features or the same. Also, there is no end point for `serve` in the `Makefile`.

**Comment by hamelsmu** [comment]
Good catch!  I've fixed this in https://github.com/fastai/nbprocess/commits/master
