### ISSUE TITLE
`_process_write` is not defined

### ISSUE THREAD

**Issue by deven367** [fastai/nbprocess#85]
Hello, is the utility for migrating from nbdev1 implemented yet? 
Upon running `nbprocess_migrate_directives` gives this error on running. 

![image](https://user-images.githubusercontent.com/31466137/175448492-7da4699e-0b3c-4f3f-8973-1cf9ea1ec82f.png)

**Comment by hamelsmu** [comment]
Thanks!  I will fix this shortly via #87
