### ISSUE TITLE
no `Makefile` in the `nbprocess_template`

### ISSUE THREAD

**Issue by deven367** [fastai/nbprocess#93]
Hey @hamelsmu, I just created a new project using `nbprocess_new` and it does not create a `Makefile`. I checked the template repo and I saw a commit with `delete Makefile`. Any thoughts on this?

**Comment by hamelsmu** [comment]
Yes you do not need a Makefile,  that has been replaced with CLI commands.  If you run `nbprocess_help` you will see all the commands.

**Comment by hamelsmu** [comment]
I've edit the tutorial to not to refer any Make commands any longer via https://github.com/fastai/nbprocess/commit/98abeb4ea4b801ca608e82dfbb04f4269351fce7
